eMalicaMVC/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace eMalicaMVC.Models
{
    public class Menu
    {
        public int Id { get; set; }

        [Display(Name = "Datum")]
        [Required(ErrorMessage = "Vnesite pravilen datum")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        public int SortId { get; set; }

        [Display(Name = "Malica")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Cena")]
        [Required]
        [Range(1, 999)]
        public decimal Price { get; set; }


    }
}

eMalicaMVC/ViewModels/SubViewModel.cs
using eMalicaMVC.Common;
using eMalicaMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eMalicaMVC.ViewModels
{
    public class SubViewModel : Menu
    {
        public List<System.Web.Mvc.SelectListItem> Weeks = new List<System.Web.Mvc.SelectListItem>();
        public IEnumerable<System.Web.Mvc.SelectListItem> Statuses {
            get {
                return Utils.GetExtraStatusList(MenuOrder?.Status);
            }
        }
        public MenuOrder MenuOrder { get; set; }
        public bool IsDisabled { get; set; }
        public string UserId;
    }
}

eMalicaMVC/Controllers/MenusController.cs
using eMalicaMVC.Common;
using eMalicaMVC.Models;
using eMalicaMVC.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eMalicaMVC.Controllers
{
    [Authorize]
    public class MenusController : Controller
    {
        MyDBHandle db = new MyDBHandle();

        //public ActionResult Admin(string userId, string dateParam)
        //{
        //    return LoadMyMenus(userId, dateParam);
        //}
        
        
        //public ActionResult Index(string dateParam)
        //{
        //    string userId = User.Identity.GetUserId();
        //    return LoadMyMenus(userId, dateParam);
        //}

        public ActionResult Index(string userId, string dateParam)
        {
            string user;

            if (!string.IsNullOrWhiteSpace(userId) && User.IsInRole("admin"))
            {
                user = userId;
            }
            else
            {
                user = User.Identity.GetUserId();
            }

            MainViewModel menuMainViewModel = new MainViewModel(user);
            
            DateTime selectedFrom;
            DateTime selectedTo;
            DateTime selectedDate;

            if (String.IsNullOrEmpty(dateParam))
            {
                selectedDate = DateTime.Now;
            }
            else
            {
                selectedDate = DateTime.Parse(dateParam);
            }
            selectedFrom = selectedDate.AddDays(-(int)selectedDate.DayOfWeek + (int)DayOfWeek.Monday);
            selectedTo = selectedDate.AddDays(-(int)selectedDate.DayOfWeek + (int)DayOfWeek.Friday);


            IEnumerable<SubViewModel> menus = db.GetMenus(user, selectedFrom, selectedTo);
            menuMainViewModel.Weeks = db.GetWeeks(selectedDate, false);
            menuMainViewModel.Users = db.GetUsers(user);
            menuMainViewModel.Menus = menus;

            foreach (var oneM in menus)
            {
                bool res = oneM.IsDisabled = menus.Any(m => m.Date == oneM.Date && m.MenuOrder != null && m.MenuOrder.Status != Enums.OrderStatus.Cancelled);
                oneM.IsDisabled = res;
            }

            return View(menuMainViewModel);
        }

        [HttpPost, Authorize(Roles = "admin")]
        public ActionResult SetOrderStatus(int orderId, string status, string dateParam)
        {
            var order = db.GetOrder(orderId);

            db.SetOrderStatus(orderId, status);

            return RedirectToAction("Index", new { userId = order.UserId, dateParam });
        }
      
        [HttpPost]
        public ActionResult Order(int id, string comment, string userId, string dateParam)
        {
            string user;

            if (!string.IsNullOrWhiteSpace(userId) && User.IsInRole("admin"))
            {
                user = userId;
            }
            else {
                user = User.Identity.GetUserId();
            }

            var menuOrder = db.GetUserMenuOrder(id, userId);

            if (menuOrder == null)
            {
                db.CreateOrder(id, comment, user);
            }
            else 
            {
                db.SetOrderStatus(menuOrder.ID, Enums.OrderStatus.Ordered, comment);
            }

        ViewBag.Message = "Your application description page.";

            return RedirectToAction("Index", new { userId, dateParam });
        }

        public ActionResult CreateOrEdit(int id = 0)
        {
            Menu menu;
            if (id == 0)//create
            {
                menu = new Menu();
                menu.Date = DateTime.Now;
                menu.Price = 5;
            }
            else
            {
                menu = db.GetMenu(id);
            }

            return View(menu);
        }

        [HttpPost]
        public ActionResult CreateOrEdit(Menu menu, int id = 0)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)//create
                {
                    db.AddMenu(menu);
                }
                else
                {
                    db.UpdateMenu(menu);
                }
                return RedirectToAction("Index", new { dateParam = menu.Date.ToString("dd-MM-yyyy")});
            }

            return View(menu);
        }

        // POST: Home/Create
        [HttpGet]
        public ActionResult Cancel(int id, string userId, string dateParam)
        {
            string user;
            if (!string.IsNullOrWhiteSpace(userId) && User.IsInRole("admin"))
            {
                user = userId;
            }
            else {
                user = User.Identity.GetUserId();
            }

            db.CancelOrder(id);
            return RedirectToAction("Index", new { userId = user, dateParam});
        }



        [HttpGet]
        public ActionResult Edit(int id, string userId)
        {
            Menu m = db.GetMenu(id);
            return RedirectToAction("CreateOrEdit", new { m });
        }

        [HttpPost]
        public bool Delete(int id, string userId)
        {
            bool ok = false;
            if (User.IsInRole("admin"))
            {
                ok = db.DeleteMenu(id);
            }
            return ok;
        }
        //// POST: Home/Create
        //[HttpPost]
        //public ActionResult Create(Menu menu)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            if (menu.Id == 0)
        //            {
        //                db.AddMenu(menu);
        //            }
        //            else
        //            {
        //                db.UpdateMenu(menu);
        //            }

        //            return RedirectToAction("Index");
        //        }
        //        catch
        //        {
        //            return View();
        //        }
        //    }
        //    else
        //    {
        //        return View(menu);
        //    }
        //}
    }
}

eMalicaMVC/Views/Menus/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

eMalicaMVC/Views/Menus/Admin.cshtml
@model eMalicaMVC.ViewModels.MenuWeeklyViewModel
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Seznam menijev za izbran teden</h2>

<div class="row">
    <div class="col-md-4">
        @Html.Label("Izbrani teden: ") @Html.DropDownList("Week", Model.Weeks, new { @class = "form-control", @style = "display:inline;width:auto" })
    </div>
    @if (this.User.IsInRole("admin"))
    {
<div class="col-md-4">
    @Html.DropDownList("Users", Model.Users, new { @class = "form-control" })
</div>
        <div class="col-md-4">
            @Html.ActionLink("Dodaj nov meni", "Create", null, new { @class = "btn btn-info" })
        </div>
    }

</div>

<div class="h4">Ponedeljek</div>
@{ Html.RenderPartial("DayOfWeek", Model.Monday); }

<div class="h4">Torek</div>
@{ Html.RenderPartial("DayOfWeek", Model.Tuesday); }

<div class="h4">Sreda</div>
@{ Html.RenderPartial("DayOfWeek", Model.Wednesday); }

<div class="h4">Četrtek</div>
@{ Html.RenderPartial("DayOfWeek", Model.Thursday); }
<div class="h4">Petek</div>
@{ Html.RenderPartial("DayOfWeek", Model.Friday); }

<script>

    $(function () {
        $("#Week").change(

            function () {
                var url = '@Html.Raw(Url.Action("Index", new { userId = Model.UserId, dateParam="CHANGEDATE" }))';

                url = url.replace("CHANGEDATE", encodeURIComponent($(this).val()));

                document.location = url;
            }
        )
        $("#Users").change(

            function () {
                var url = '@Html.Raw(Url.Action("Admin", new {  userId = "change" }))';
                url = url.replace("change", encodeURIComponent($(this).val()));
                document.location = url;
            }
        )

        $(".naroci").click(function () {
            var komentar = prompt("Vnesi komentar");

        })
    })
</script>

eMalicaMVC/Views/Menus/CreateOrEdit.cshtml
@model eMalicaMVC.Models.Menu

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Urejanje malice</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "date-picker"} })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Name, new { cols = 35, @rows = 3, htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Shrani" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Nazaj na seznam", "Index")
</div>

eMalicaMVC/Views/Menus/Index.cshtml
@model eMalicaMVC.ViewModels.MainViewModel
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Seznam menijev za izbran teden</h2>
<div class="row">
    <div class="col-md-4">
        @Html.Label("Izbrani teden: ") @Html.DropDownList("Week", Model.Weeks, new { @class = "form-control", @style = "display:inline;width:auto" })
    </div>
    @if (this.User.IsInRole("admin"))
    {
        <div class="col-md-4">
            @Html.DropDownList("Users", Model.Users, new { @class = "form-control" })
        </div>
        <div class="col-md-4">
            @Html.ActionLink("Dodaj nov meni", "CreateOrEdit", new { @class = "btn btn-info" })
        </div>
    }
</div>
<h4>Ponedeljek</h4>
@{Html.RenderPartial("SubView", Model.Menus.Where(m => m.Date.DayOfWeek == DayOfWeek.Monday));}
<h4>Torek</h4>
@{ Html.RenderPartial("SubView", Model.Menus.Where(m => m.Date.DayOfWeek == DayOfWeek.Tuesday)); }
<h4>Sreda</h4>
@{ Html.RenderPartial("SubView", Model.Menus.Where(m => m.Date.DayOfWeek == DayOfWeek.Wednesday)); }
<h4>Četrtek</h4>
@{ Html.RenderPartial("SubView", Model.Menus.Where(m => m.Date.DayOfWeek == DayOfWeek.Thursday)); }
<h4>Petek</h4>
@{ Html.RenderPartial("SubView", Model.Menus.Where(m => m.Date.DayOfWeek == DayOfWeek.Friday)); }
<script>
    $(function () {
        $("#Week").change(

            function () {
                var url = '@Html.Raw(Url.Action("Index", new { userId = Model.UserId, dateParam="CHANGEDATE" }))';

                url = url.replace("CHANGEDATE", encodeURIComponent($(this).val()));

                document.location = url;
            }
        )
            $("#Users").change(

            function () {
                var url = '@Html.Raw(Url.Action("Index", new {  userId = "change", dateParam = "CHANGEDATE" }))';
                    url = url.replace("change", encodeURIComponent($(this).val()));
                    url = url.replace("CHANGEDATE", encodeURIComponent($('#Week').val()));
                document.location = url;
            }
        )
        $(".naroci").click(function () {
            var komentar = prompt("Vnesi komentar");
        })
    })
</script>

eMalicaMVC/Views/Menus/SubView.cshtml
@model IEnumerable<eMalicaMVC.ViewModels.SubViewModel>

@if (Model.Count() < 1)
{
    <div>ni malic</div>
}

@foreach (var item in Model)
 {
    <div class="row menuRow">
        <div class="col-md-4">
            @item.Name
        </div>
        @if (User.IsInRole("admin"))
        {
        <div class="col-md-1">
            <a href="@Url.Action("CreateOrEdit", "Menus", new { id = item.Id, userId = item.UserId, dateParam = item.Date.ToString("dd-MM-yyyy") })">
                <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#286090; font-size:large;"></i>
            </a>
            &nbsp;
            <a href="@Url.Action("Delete", "Menus", new { id = item.Id, userId = item.UserId })" class="delete-link">
                <i class="fa fa-trash" aria-hidden="true" style="color:#286090;font-size:large;"></i>
            </a>
        </div>
        }
        <div class="col-md-1">
            @item.Price
        </div>
        <div class="col-md-4">
            @*<img class="check @(item.MenuOrder?.Status == eMalicaMVC.Common.Enums.OrderStatus.Ordered ? "visible" : "hidden")" src="~/Content/check.png" />*@
            @if (!item.IsDisabled)
            {
                using (Html.BeginForm("Order", "Menus", FormMethod.Post)) // form for ordering
                {
                    if (User.IsInRole("admin"))
                    {
                        @Html.TextBox("Comment", item.MenuOrder?.Comment);
                    }

                    @Html.Hidden("id", item.Id);
                    @Html.Hidden("userId", item.UserId);
                    @Html.Hidden("dateParam", item.Date.ToString("dd-MM-yyyy"));

                    <input type="submit" value="Naroči" class="btn btn-primary" />
                }
            }
            else if (item.MenuOrder != null && item.MenuOrder?.Status != eMalicaMVC.Common.Enums.OrderStatus.Cancelled)
            {
                <table border="0">
                    <tr>
                        <td>
                            @if (User.IsInRole("admin"))
                            {
                                using (Html.BeginForm("SetOrderStatus", "Menus", FormMethod.Post))
                                {
                                    @Html.Hidden("orderID", item.MenuOrder.ID);
                                    @Html.Hidden("dateParam", item.Date.ToString("dd-MM-yyyy"));
                                    @Html.DropDownList("Status", item.Statuses, new { onchange = "this.form.submit();", @class = "form-control", style = "width:auto;display:inline-block;margin-right:5px;" })
                                    @*<input type="submit" value="Spremeni status" class="btn btn-primary inline" />*@
                                }
                            }
                        </td>
                        <td>
                            @Html.ActionLink("Prekliči", "Cancel", new { id = item.MenuOrder.ID, userId = item.UserId, dateParam=item.Date.ToString("dd-MM-yyyy") }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                </table>
            }
        </div>
        <div class="col-md-2">
            @if (item.MenuOrder != null)
            {
                @item.MenuOrder.Comment;
            }
        </div>
    </div>
    }
    <br />